spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crudfinal
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 713034844949-gciq5kg7hro5lun087tibvblv7gago94.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://www.googleapis.com/oauth2/v4/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
            jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs

jwt:
  secret: XmepQ0SjGUHlT2fm5b2ENMlliVamwQvKpWs8eCTh6Mx6a9yeDtmmnopHNUZn8VPVcRf77pkQDiyBgmuK7cmg3w==
  access-token-validity-in-milliseconds: 3600000
