spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crudfinal
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        show_sql: true
    open-in-view: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 713034844949-gciq5kg7hro5lun087tibvblv7gago94.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://www.googleapis.com/oauth2/v4/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
            jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
  main: # 추가된 부분 시작
    allow-circular-references: true # 순환 참조 허용 설정
  # 추가된 부분 끝

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace

jwt:
  secret: XmepQ0SjGUHlT2fm5b2ENMlliVamwQvKpWs8eCTh6Mx6a9yeDtmmnopHNUZn8VPVcRf77pkQDiyBgmuK7cmg3w==
  access-token-validity-in-milliseconds: 3600000 # 1시간 (ms)